### ISSUE TITLE
Create Log info for each button press

### ISSUE THREAD

**Issue by m12watanabe1a** [HarvestX/ps_ros2_common#1]
たぶんここのコードを走らせるだけで目的は完了すると思います！

リポジトリがちゃんと機能しているかどうか確認していただけますと幸いです！

https://github.com/HarvestX/ps_ros2_common/blob/main/src/example_joy.cpp

**Comment by kobayashi-na** [comment]
とりあえず動いていることは確認しました！

**Comment by kobayashi-na** [comment]
turtlesimと連動して、cmd_velをコントローラから操作できるようにしました。
